### ISSUE TITLE
Add Banner and Ownership properties to common-schemas/packs.schema.json added in v11

### ISSUE THREAD

**Issue by MaxPat931** [AceKokuren/foundry-schemas#19]
Note that the path to the banner image isn't relative, I think that suggested dimensions are ~350x85
Ownership info - https://github.com/foundryvtt/foundryvtt/issues/9318

![image](https://github.com/AceKokuren/foundry-schemas/assets/86370342/6ebb8ef2-2574-4ec5-815c-5e0b7e7b21a0)

**Comment by AceKokuren** [comment]
Will check banner path and implement.
